//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bishwas_book_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class image_table
    {
        public int image_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string image_path { get; set; }
    
        public virtual product_table product_table { get; set; }
    }
}
