//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bishwas_book_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details_table
    {
        public int details_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> order_quantity { get; set; }
        public Nullable<decimal> order_price { get; set; }
        public Nullable<decimal> order_total { get; set; }
    
        public virtual order_table order_table { get; set; }
        public virtual product_table product_table { get; set; }
    }
}
